2024-03-15 12:34:57,878 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:55497a10-e29a-11ee-8da7-acde48001122
2024-03-15 12:34:57,878 — main.py:66 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:55497a10-e29a-11ee-8da7-acde48001122
2024-03-15 12:44:16,315 — answer_generator.py:66 -             generate() — INFO — [] - answer_id:55497a10-e29a-11ee-8da7-acde48001122: time taken to generate result : 558.4369421005249 : 
2024-03-15 12:44:16,351 — main.py:122 -     get_qna_response() — ERROR — [] - InternalError: Object of type Response is not JSON serializable :Traceback (most recent call last):;  File "/Users/reverma/git/custom-rag-pipeline/src/main.py", line 90, in get_qna_response;    return Response(qa_gen.generate());  File "/Users/reverma/git/custom-rag-pipeline/src/answer_generator.py", line 70, in generate;    json_string = json.dumps(;  File "/Users/reverma/anaconda3/envs/test_gr/lib/python3.8/json/__init__.py", line 234, in dumps;    return cls(;  File "/Users/reverma/anaconda3/envs/test_gr/lib/python3.8/json/encoder.py", line 199, in encode;    chunks = self.iterencode(o, _one_shot=True);  File "/Users/reverma/anaconda3/envs/test_gr/lib/python3.8/json/encoder.py", line 257, in iterencode;    return _iterencode(o, 0);  File "/Users/reverma/anaconda3/envs/test_gr/lib/python3.8/json/encoder.py", line 179, in default;    raise TypeError(f'Object of type {o.__class__.__name__} ';TypeError: Object of type Response is not JSON serializable;
2024-03-15 12:44:48,265 — main.py:63 -     get_qna_response() — INFO — [] - answer_id:b52f5c96-e29b-11ee-8da7-acde48001122
2024-03-15 12:44:48,265 — main.py:66 -     get_qna_response() — INFO — [] - Starting to serve request:answer_id:b52f5c96-e29b-11ee-8da7-acde48001122
